### PR TITLE
✂️ add url trimming

### LINKED ISSUE #16: Whitespace causes invalid URL
**Describe the bug**
Whitespace in the URL field of AddFeedActivity causes the program to throw Invalid URL.

**To Reproduce**
1. Press the button to add a feed.
2. Enter an otherwise valid URL.
3. Add a space or "\n" character to the URL
4. Submit the URL.
5. Recieve an error "Invalid URL."
6. The feed is not added.

**Expected behavior**
The program should trim whitespace.

### PR DESCRIPTION
**Pull request by simonchenwastaken**
Closes #16 

Added url trimming to `AddFeedActivity.kt`
Haven't tested it yet in an emulator or device.

### CODE REVIEW

File: app/src/main/java/monster/minions/binocularss/activities/AddFeedActivity.kt [hunk 1]
```diff
@@ -154,9 +154,10 @@ class AddFeedActivity : ComponentActivity() {
...
      */
     private fun addHttps(url: String): String {
+        var trimmedUrl = url.trim(' ');
         return when {
-            url.startsWith("https://") || url.startsWith("http://") -> url
-            else -> "https://$url"
+            trimmedUrl.startsWith("https://") || trimmedUrl.startsWith("http://") -> trimmedUrl
+            else -> "https://$trimmedUrl"
         }
     }
```
Comment (hisbaan) [inline app/src/main/java/monster/minions/binocularss/activities/AddFeedActivity.kt:162]: I would recommend not trimming the URL here, but instead where the input is actually captured in submit() (i.e. the value that is passed into this function). Doing it here kind of violates SOLID as this function should purely be adding http/https, and not trimming the URL. Also, var should not be used here since we are not modifying the variable, instead val should be used to make the variable immutable. Good implementation thought, does this also cover if the user were to somehow insert a newline character ("\n") like Yaniv did?

**Comment by hisbaan** [comment]
So I just tested this since you've been having trouble with your emulator and I was able to come up with a setup for it not to work:
1. Open an external app, type a URL, press enter
2. Copy this typed content (including the newline character)
3. Paste this into the box
4. Press enter
The app will accept the URL but nothing will happen. We should try and fix this by checking for newline characters if there is a way to do so. If not, then it isn't of the highest priority since that "workflow" is not and will not be common.

**Review by eamonma — APPROVED** [review]
Well-documented, could add some tests.

**Review by taizhng — COMMENTED** [review]
The \n still doesn't work during testing... overall the comments are great and my opinion is similar to Eamon's, testing would be very important!

**Comment by simonchenwastaken** [comment]
I added a test, gonna merge the PR now 😊
